/**
 * Shared SEO constants and structured-data helpers.
 *
 * Kept separate from BaseLayout so the Organization identity is written once
 * and referenced by @id from every other schema on the site, rather than being
 * restated (and drifting) page by page.
 */

export const SITE_NAME = 'Redrock Strategic Advisors';
export const SITE_URL = 'https://redrocksa.com';
export const TITLE_SUFFIX = ` | ${SITE_NAME}`;

/** Default social share image. 1200x630, generated by scripts/generate-og-image.mjs. */
export const DEFAULT_OG_IMAGE = '/og-default.png';

/** Stable @id for the firm, so Person/Service/Breadcrumb nodes can point at it. */
export const ORG_ID = `${SITE_URL}/#organization`;

/**
 * Serializes structured data for injection via `set:html`.
 *
 * JSON.stringify alone is NOT safe inside a <script> block: a "</script>"
 * appearing in any string value closes the tag early and breaks the rest of
 * the page. Escaping the angle brackets keeps the JSON valid (< is a
 * legal JSON escape) while making early termination impossible.
 */
export function serializeJsonLd(data: unknown): string {
  return JSON.stringify(data)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026');
}

/** Absolute URL from a site-relative path. Social scrapers ignore relative ones. */
export function absoluteUrl(path: string, site: URL | undefined = undefined): string {
  return new URL(path, site ?? SITE_URL).toString();
}

/**
 * The firm itself. FinancialService rather than plain Organization because
 * Redrock is an advisory business with a real street address — it gives search
 * engines a category, not just a name.
 */
export const organizationSchema = {
  '@type': 'FinancialService',
  '@id': ORG_ID,
  name: SITE_NAME,
  legalName: 'Redrock Strategic Advisors LLC',
  url: `${SITE_URL}/`,
  logo: {
    '@type': 'ImageObject',
    url: `${SITE_URL}/RSA_color.png`,
  },
  image: `${SITE_URL}/RSA_color.png`,
  email: 'info@redrocksa.com',
  // Profiles that confirm this site and the real-world firm are the same
  // entity. Without it, search engines have only the domain to go on when
  // resolving a brand query.
  sameAs: ['https://www.linkedin.com/company/redrock-strategic-advisors/'],
  description:
    'Redrock Strategic Advisors partners with middle-market business owners on mergers and acquisitions, capital advisory, and strategic and board advisory engagements.',
  address: {
    '@type': 'PostalAddress',
    streetAddress: '138 E 12300 S, Unit #810',
    addressLocality: 'Draper',
    addressRegion: 'UT',
    postalCode: '84020',
    addressCountry: 'US',
  },
  areaServed: {
    '@type': 'Country',
    name: 'United States',
  },
  knowsAbout: [
    'Mergers and Acquisitions',
    'Capital Advisory',
    'Strategic and Board Advisory',
    'Middle-Market Investment Banking',
  ],
};

/**
 * Breadcrumb trail from a list of [name, path] pairs.
 * Home is prepended automatically; pass the rest in order.
 */
export function breadcrumbSchema(trail: [string, string][]) {
  return {
    '@type': 'BreadcrumbList',
    itemListElement: [['Home', '/'], ...trail].map(([name, path], i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name,
      item: `${SITE_URL}${path}`,
    })),
  };
}
